config/routes.rb
Hacklaunch::Application.routes.draw do

  resources :sign_ups

  root 'sign_ups#new'

end

app/models/sign_up.rb
class SignUp < ActiveRecord::Base
  validates :name,  :presence => true, 
                    :length => {:minimum => 1, :maximum => 254}
                   
  validates :email, :presence => true, 
                    :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

  def image_url
    url = Gravatar.new(email).image_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  def new
    @sign_up_count = SignUp.count
    @sign_up = SignUp.new
  end

  def create
    SignUp.create(params.require(:sign_up).permit(:name, :email))
    redirect_to sign_ups_path
  end
  
  def index
    @sign_up = SignUp.all
  end

  def destroy
    redirect_to sign_ups_path
  end

  def edit
    @sign_up = SignUp.find(params[:id])
  end

  def update
    @sign_up = SignUp.find(params[:id])
    @sign_up.update(params.require(:sign_up).permit(:name, :email))
    redirect_to sign_ups_path
  end

  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacklaunch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='page-header'>
      <h1>HackLaunch <small>Actual product TBD</small></h1>
    </div>
    <%= yield %>
  <div class="container">    
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-6">
        <ul class="list-unstyled">
          <li>GitHub<li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>
      <div class="col-md-6">
        <ul class="list-unstyled">
          <li>Documentation<li>
          <li><a href="#">Product Help</a></li>
          <li><a href="#">Developer API</a></li>            
        </ul>
      </div>  
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-md-8">
        <a href="#">Terms of Service</a>    
        <a href="#">Privacy</a>    
        <a href="#">Security</a>
      </div>
      <div class="col-md-4">
        <p class="muted pull-right">© 2014 Jordan Saxe. All rights reserved</p>
      </div>
    </div>
  </div>
</div>
  </div>
</body>
</html>

app/views/sign_ups/edit.html.erb
<%=form_for @sign_up, class: 'form' do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
    <%= f.submit "Submit", class: 'btn btn-default' %>
<% end %>

app/views/sign_ups/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @sign_up.each do |sign_up| %>
      <tr>
        <td><%= image_tag sign_up.image_url %></td>
        <td><%= sign_up.name %></td>
        <td><%= sign_up.email %></td>
        <td><%=link_to('Edit a user', edit_sign_up_path(sign_up)) %></td>
        <td><%=link_to('Delete a user', sign_up_path(sign_up.id), method: :delete) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sign_ups/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Sign up to be a part of the beta and to receive updates!</h1>
  </div>
</div>


<div class="container">
  <%=form_for @sign_up, class: 'form-inline' do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <%= f.submit "Submit", class: 'btn btn-default' %>
  <% end %>
  
    <p> <%= @sign_up_count %> number of people have signed up </p>
  </div>
</div>

app/views/sign_ups/show.html.erb
<p>Thanks for signing up <%= @sign_up.name %>. We will email you soon at <%= @sign_up.email %> when we are ready.</p>

app/views/signups/view.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Sign up to be a part of the beta and to receive updates!</h1>
  </div>
</div>


<div class="container">
  <div class="form-inline">
    <% if not @hide_form %>
      <%=form_tag '/' do %>
      <div class="form-group">
          <input type='text' name='name' placeholder='Enter Name'>
      </div>
      <div class="form-group">
        <input type='text' name='email' placeholder='Enter Password'>
      </div>
        <input type='submit' class="btn btn-default" /> 
      <% end %>
    <% end %>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
      <% else %>
    <% end %>

    <% if flash[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
      <% else %>
    <% end %>

    <p> <%= @sign_up_count %> number of people have signed up </p>
  </div>
</div>